# Força o Xorg a não "sequestrar" a GPU secundária automaticamente
Section "ServerFlags"
    Option "AutoAddGPU" "off"
EndSection

# Sobrescreve a regra do OutputClass do /usr/share/
Section "OutputClass"
    Identifier "nvidia-fix"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    # Garante que a Intel continue sendo a primária
    Option "PrimaryGPU" "no"
EndSection
