#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Windows Boot Manager (em /dev/nvme0n1p1)' --class windows --class os $menuentry_id_option 'osprober-efi-8C03-8B79' {
        insmod part_gpt
        insmod fat
        search --no-floppy --fs-uuid --set=root 8C03-8B79
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
